version: '3.1'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql:/data/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/mongodb
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  rabbitmq:
    image: rabbitmq:3
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/data/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq/
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  arangodb:
    image: arangodb:latest
    ports:
        - 8529:8529
    volumes:
        - arangodb_data_container:/var/lib/arangodb3
        - arangodb_apps_data_container:/var/lib/arangodb3-apps
    env_file:
      - .env
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
volumes:
  mysql:
    external: true
  mongodb:
    external: true
  rabbitmq_data:
    external: true
  rabbitmq_log:
    external: true  
  arangodb_data_container:
    external: true
  arangodb_apps_data_container:
    external: true
  redisdb:
    external: true
  dynamodb:
    external: true